Resources:
  LambdaRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ["sts:AssumeRole"]
    Path: /
    Policies:
      - PolicyName: LoggingAccess
        PolicyDocument:
          Statement:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
      - PolicyName: S3FullAccessNoDelete
        #! This is way to broad for production use! Remember this is an example only.
        PolicyDocument:
          Statement:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - "s3:Get*"
                  - "s3:Put*"
                  - "s3:List*"

Outputs:
  SlsLambdaTestingRole:
    Description: The name of the ECS cluster
    Value: !GetAtt "LambdaRole.Arn"
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SlsLambdaTestingRole"]]
