service: sls-sample

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage,'dev'}
  region: us-east-1
  role: ${cf:${opt:iam-stack-name}.SlsLambdaTestingRole}

functions:
  hello:
    handler: handler.hello

    events:
      - schedule: rate(10 minutes)

environment:
  STAGE: ${self:provider.stage}
  BUCKETPREFIX: ${opt:bucket-prefix}

resources:
 Resources:
   SampleBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${opt:bucket-prefix}-${self:provider.stage}-sls-testing-bucket
